runtime: python27
api_version: 1
threadsafe: false

application: robinnbrewer
version: 1


handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|pdf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf))

- url: .*
  script: main.py



